cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/pradeepkumar/ns-allinone-3.15/ns-3.15/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Tools/c_config.py", line 445, in run_c_code\n    bld.compile()\n  File "/home/pradeepkumar/ns-allinone-3.15/ns-3.15/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Build.py", line 190, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139833343220048: cxx test.cc -> test.cc.1.o}\n[\'/usr/bin/g++\', \'-O0\', \'-ggdb\', \'-g3\', \'-Wall\', \'-Werror\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DHAVE_PYTHON_H=1\', \'../test.cc\', \'-c\', \'-o\', \'test.cc.1.o\']\n'
